# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PracowniaTm https://github.com/vealen/PracowniaTM.git
                                 A QGIS plugin
 Autoprojekt+algorytmy
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-13
        copyright            : (C) 2022 by Piotr Fiodor
        email                : pfiodor@taxusul.com.pl
        git sha              : $Format:%H$
 ***************************************************************************/

 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PracowniaTm class from file PracowniaTm.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pracownia_tm import PracowniaTm
    return PracowniaTm(iface)
